# Database credentials to store data
database:
  host: [DatabaseHost]
  database: [DatabaseName]
  user: [Username]
  password: [UserPassword]

# Rank configuration for the server
ranks:
  rankName1: # Enter as many ranks as you want (playtime is in minutes)
    id: [RankID] # This ID will determine the rank order in the tablist
    color: [RankColor]
    prefix: [RankPrefix]
    playtime: 0 # If playtime is set to -1 the rank will be unobtainable through playtime
    maxHomes: 0 # If maxHomes is set to -1 the max amount of homes will be infinite
  
  rankName2:
    id: [RankID]
    color: [RankColor]
    prefix: [RankPrefix]
    playtime: 0
    maxHomes: 0 