# Database credentials to store data
database:
  host: [DatabaseHost]
  database: [DatabaseName]
  user: [Username]
  password: [UserPassword]

# Max amount of teleportation requests per player. Set to -1 for an infinite amount
maxTeleports: 5

# Your discord bot token obtainable via the discord dev portal
token: [token]

# The discord webhook URL that the bot will use to communicate player activity, it's avatar can be any image on the internet
webhookURL: [webhookURL]
webhookAvatarURL: [avatarURL]

# The discord channel id that the bot will get messages from to send to the minecraft server
channel: [ChannelID]

# The bot's status. {playerCount} will be replaced with actual server player count, same with {maxPlayers}
status: "{playerCount} / {maxPlayers}"

# The minimum area size to create one
minimumArea: 256
minAreaWidthX: 16
minAreaWidthY: 16

# Rank configuration for the server
ranks:
  rankName1: # Enter as many ranks as you want (playtime is in minutes)
    id: [RankID] # This ID will determine the rank order in the tablist
    name: [RankName]
    color: [RankColor]
    prefix: [RankPrefix]
    playtime: 0 # If playtime is set to -1 the rank obtaiable via OP
    maxHomes: 0 # If maxHomes is set to -1 the max amount of homes will be infinite
  
  rankName2:
    id: [RankID]
    name: [RankName]
    color: [RankColor]
    prefix: [RankPrefix]
    playtime: 0
    maxHomes: 0 