# Database credentials to store data
database:
  host: [DatabaseHost]
  database: [DatabaseName]
  user: [Username]
  password: [UserPassword]

# Tablist title & footer
header: [header]
footer: [footer]

# Max amount of teleportation requests per player. Set to -1 for an infinite amount
maxTeleports: 5

# Your discord bot token obtainable via the discord dev portal
token: [token]

# The discord webhook URL that the bot will use to communicate player activity, it's avatar can be any image on the internet
webhookURL: [webhookURL]
webhookAvatarURL: [avatarURL]

# The discord channel id that the bot will get messages from to send to the minecraft server
channel: [ChannelID]

# The role that will be attributed to memebers that link their account
linkedRole: [linkedRokeID]

# The bot's status. {playerCount} will be replaced with actual server player count, same with {maxPlayers}
status: "{playerCount} / {maxPlayers}"

# The minimum area size to create one, by default a chunk
minimumArea: 256
minAreaWidthX: 16
minAreaWidthY: 16

# Passive claim blocks earnings, interval is in minutes, by default 77 every 30 minutes
claimAmount: 75
claimInterval: 30

# Rank configuration for the server
ranks:
  rankName1: # Enter as many ranks as you want (playtime is in minutes)
    id: [RankID] # This ID will determine the rank order in the tablist
    name: [RankName] # Rank display names
    color: [RankColor] # Rank color
    prefix: [RankPrefix] # rank prefix
    playtime: 0 # If playtime is set to -1 the rank obtaiable via OP
    maxHomes: 0 # If maxHomes is set to -1 the max amount of homes will be infinite
    claimBonus: 0 # Amount of claim blocks given to player when obtaining this rank
    discordRole: [roleID] # Discord role that corresponds to rank
  
  rankName2:
    id: [RankID]
    name: [RankName]
    color: [RankColor]
    prefix: [RankPrefix]
    playtime: 0
    maxHomes: 0
    claimBonus: 0
    discordRole: [roleID]